# Generated by Django 3.1.2 on 2022-07-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='preco',
        ),
    ]
