# Generated by Django 3.1.2 on 2022-08-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20220802_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
    ]
